DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    email TEXT NULL,
    addr TEXT NULL,
    phone INTEGER NULL,
);

CREATE TABLE saved_locations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mapper_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  addr TEXT NOT NULL,
  lat FLOAT(8) NOT NULL,
  long FLOAT(8) NOT NULL,
  FOREIGN KEY (mapper_id) REFERENCES user (id)
);